### ISSUE TITLE
Calendar Events

### ISSUE THREAD

**Issue by kennetpostigo** [clauderic/react-infinite-calendar#8] opened 2016-06-03 18:04 UTC
Is it possible to add Events to the calendar? Like say programmatically load in upcoming events and have them highlighted?

**Comment by clauderic** [comment] 2016-06-03 18:06
Not currently, but there is a proposed approach to handling this. Duplicate of https://github.com/clauderic/react-infinite-calendar/issues/6, please discuss there

**Closed** 2016-06-03 18:43 UTC
