### ISSUE TITLE
"Select Year First" Gets Months Wrong

### ISSUE THREAD

**Issue by hdon** [clauderic/react-infinite-calendar#124] opened 2017-06-15 16:21 UTC
I'm using stock Chromium on Ubuntu Xenial.

When you click on the "Select Year First" option on the left-hand side of the demo page, what you get isn't quite right.

http://clauderic.github.io/react-infinite-calendar/#/customization/select-year-first?_k=tmpazw

http://imgur.com/a/yKvix

My Chromium version is 58.0.3029.110 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

http://imgur.com/a/X3Pwt

There's also an error in the console:

http://imgur.com/a/AuDXI

**Comment by jinalex** [comment] 2017-06-29 16:52
+1

**Comment by clauderic** [comment] 2017-11-10 19:42
Closing as duplicate of #140, will discuss there.

**Closed by clauderic** 2017-11-10 19:42 UTC
