### ISSUE TITLE
react-addons-css-transition-group is deprecated

### ISSUE THREAD

**Issue by syko** [clauderic/react-infinite-calendar#121] opened 2017-05-29 11:56 UTC
Should use https://github.com/reactjs/react-transition-group instead.

From https://www.npmjs.com/package/react-addons-css-transition-group:
> In particular, its version 1.1.1 is a drop-in replacement for the last released version of react-addons-css-transition-group.

**Comment by clauderic** [comment] 2017-05-29 12:38
Duplicate of #113. 

This was already addressed by 8873620, just update to the latest version to get the fix :)

**Closed by clauderic** 2017-05-29 12:38 UTC

**Comment by dashed** [comment] 2017-07-06 14:46
fyi, `react-addons-css-transition-group` is still mentioned on the `README.md`

**Comment by snaerth** [comment] 2017-09-29 08:34
You should update your README.md from **react-addons-css-transition-group** to **react-transition-group**
